name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: 'latest'
        cabal-version: 'latest'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # We do not bother caching Python dependencies since we do not have many, as
    # https://docs.github.com/en/actions/guides/building-and-testing-python
    # indicates that this may have a negative impact on performance.

    - name: Cabal cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Magnolia dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Build
      run: make

    - name: Run pass tests
      run: make tests-all-passes

    - name: Run frontend tests
      run: make tests-frontend
